---
- name: Manage Mariadb users to create
  include_tasks: shared/user_conf.yml
  loop: "{{ mariadb_users_create }}"
  loop_control:
    loop_var: user
  when: mariadb_users_create|length > 0

- name: Manage Mariadb users to remove
  include_tasks: shared/user_conf.yml
  loop: "{{ mariadb_users_remove }}"
  loop_control:
    loop_var: user
  when: mariadb_users_remove|length > 0
...
