---
- name: Manage Mariadb users to create
  mysql_user:
    name: "{{ item.0.name }}"
    host: "{{ item.1 | default('localhost') }}"
    password: "{{ item.0.password }}"
    priv: "{{ item.0.privs | join('/') | default('*.*:USAGE') }}"
    state: present
    append_privs: "{{ item.0.append_privs | default('no') }}"
  with_subelements:
    - "{{ mariadb_users_create }}"
    - hosts
  no_log: true
  when: mariadb_users_create|length > 0

- name: Manage Mariadb users to remove
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    host_all: "{{ item.host_all | default('no') }}"
    state: absent
  with_items:
    - "{{ mariadb_users_remove }}"
  when: mariadb_users_remove|length > 0
...
