---

- name: Install epel-release
  yum:
    name: "epel-release" 
    state: installed


- name: Install packages
  yum:
    name: "{{ mariadb_packages + mariadb_packages_centos8 }}" 
    state: installed

...